# Generated by Django 5.2.16 on 2026-07-23 16:25

import uuid
from django.db import migrations, models


def prepare_legacy_userprofile_table(apps, schema_editor):
    table_name = 'attendance_userprofile'

    def columns():
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(f'PRAGMA table_info({table_name})')
            return {row[1] for row in cursor.fetchall()}

    existing_columns = columns()
    with schema_editor.connection.cursor() as cursor:
        if 'student_id' in existing_columns and 'employee_id' not in existing_columns:
            cursor.execute(f'ALTER TABLE {table_name} RENAME COLUMN student_id TO employee_id')
            existing_columns = columns()

        if 'qr_token' not in existing_columns:
            cursor.execute(f'ALTER TABLE {table_name} ADD COLUMN qr_token varchar(64)')

        cursor.execute(f'SELECT id, employee_id, qr_token FROM {table_name} ORDER BY id')
        rows = cursor.fetchall()

        seen_employee_ids = set()
        seen_qr_tokens = set()
        for row_id, employee_id, qr_token in rows:
            next_employee_id = employee_id
            if not next_employee_id or next_employee_id in seen_employee_ids:
                next_employee_id = f'LEGACY-{row_id}'
            seen_employee_ids.add(next_employee_id)

            next_qr_token = qr_token
            if not next_qr_token or next_qr_token in seen_qr_tokens:
                next_qr_token = uuid.uuid4().hex[:16]
                while next_qr_token in seen_qr_tokens:
                    next_qr_token = uuid.uuid4().hex[:16]
            seen_qr_tokens.add(next_qr_token)

            cursor.execute(
                f'UPDATE {table_name} SET employee_id = %s, qr_token = %s WHERE id = %s',
                [next_employee_id, next_qr_token, row_id],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(prepare_legacy_userprofile_table, migrations.RunPython.noop),
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
